config/routes.rb
Rails.application.routes.draw do
  resources :genres
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'movies#index'

  get 'movies/filter/:filter' => 'movies#index', as: :filtered_movies
  # Another form:
  # (I'm not sure which I prefer, but I tend towards the "hash rocket" one)
  # get 'movies/filter/:filter', to: 'movies#index', as: :filtered_movies

  resources :movies do
    resources :reviews
    resources :favorites, only: [:create, :destroy]
  end

  # Making it a singular session since there will only ever be one
  # https://api.rubyonrails.org/classes/ActionDispatch/Routing/Mapper/Resources.html#method-i-resource
  # https://guides.rubyonrails.org/routing.html#singular-resources
  # resources :sessions, only: %i[new create destroy]
  resource :session, only: %i[new create destroy]
  get 'signin', to: 'sessions#new'

  resources :users
  get 'signup', to: 'users#new'
end

app/views/layouts/_flash.html.erb
<%# if flash[:notice] %>
<!--  <div class="flash notice">-->
    <%#= flash[:notice] %>
<!--  </div>-->
<%# end %>

<%# if flash[:alert] %>
<!--  <div class="flash alert">-->
    <%#= flash[:alert] %>
<!--  </div>-->
<%# end %>

<% flash.each do |type, message| %>
  <%= content_tag(:div, message, class: "flash #{type}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <p>
    Copyright &copy; <%= Time.now.year %>
    <%= link_to "Michael Westphal", "https://github.com/michaelwestphal" %>
  </p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav>
    <%= link_to image_tag("logo.png", alt: "Logo"), root_path %>
    <ul class="left">
      <li>
        <%# NOTE: root_path and movies_path point to the same location at the moment.  %>
        <%= nav_link_to "Released", movies_path %>
      </li>
      <li>
        <%= nav_link_to "Upcoming", filtered_movies_path(:upcoming) %>
      </li>
      <li>
        <%= nav_link_to "Recent", filtered_movies_path(:recent) %>
      </li>
      <li>
        <%= nav_link_to "Hits", filtered_movies_path(:hits) %>
      </li>
      <li>
        <%= nav_link_to "Flops", filtered_movies_path(:flops) %>
      </li>
    </ul>
    <ul class="right">
      <% if current_user %>
        <li>
          <%= link_to current_user.name, current_user %>
        </li>
        <li>
          <%= link_to "Account Settings", edit_user_path(current_user) %>
        </li>
        <li>
          <%# Link or Button here. Which should I prefer? Or is it really preference? 
              One nice thing about button_to is it is easier to type and read. %>
          <%# link_to "Sign Out", session_path, data: { turbo_method: :delete }, class: "button" %>
          <%= button_to "Sign Out", session_path, method: :delete %>
        </li>
      <% else %>
        <li>
          <%= link_to "Sign In", signin_path, class: "button" %>
        </li>
        <li>
          <%= link_to "Sign Up", signup_path, class: "button" %>
        </li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fantastic Flix!</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- I learned about SimpleCSS during DHH's intro to Rails 7 video.
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    -->

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%= render "layouts/header" %>

    <div class="content">
      <%= render "layouts/flash" %>
      <%= yield %>
    </div>

    <%= render "layouts/footer" %>
  </body>
</html>